### ISSUE TITLE
registry store error: no schema has been selected

### ISSUE THREAD

**Issue by yingding** [nossrannug/feast-postgres#8]
While putting the registry to postgres db instead of local registry with the following setting in `feature_story.yaml`
```
...
registry:
    registry_store_type: feast_postgres.PostgreSQLRegistryStore
    path: feast_registry    # This will become the table name for the registry
    host: xxxxx
    port: xxxxxx     # Optional, default is 5432
    database: xxxxxx
    db_schema: registry_feature_store
    user: xxxxxxx
    password: xxxxxxx
```
After I have run `feast apply`, i got the following error:
```
Registered entity driver_id
Registered feature view driver_hourly_stats
Deploying infrastructure for driver_hourly_stats
Traceback (most recent call last):
  File "/opt/conda/bin/feast", line 8, in <module>
    sys.exit(cli())
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/feast/cli.py", line 369, in apply_total_command
    apply_total(repo_config, repo, skip_source_validation)
  File "/opt/conda/lib/python3.8/site-packages/feast/usage.py", line 280, in wrapper
    raise exc.with_traceback(traceback)
  File "/opt/conda/lib/python3.8/site-packages/feast/usage.py", line 269, in wrapper
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/feast/repo_operations.py", line 262, in apply_total
    registry.commit()
  File "/opt/conda/lib/python3.8/site-packages/feast/registry.py", line 661, in commit
    self._registry_store.update_registry_proto(self.cached_registry_proto)
  File "/opt/conda/lib/python3.8/site-packages/feast_postgres/registry_store.py", line 56, in update_registry_proto
    cur.execute(
psycopg2.errors.InvalidSchemaName: no schema has been selected to create in
LINE 2:                     CREATE TABLE IF NOT EXISTS "feast_regist...
```

My feast-postgres version is v0.2.0

**Comment by nossrannug** [comment]
Hey @yingding,
Can you upgrade to v0.2.1? I think this issue was fixed in that version.

**Comment by yingding** [comment]
@nossrannug 
Thanks for your rapid response and great work, indeed v0.2.1 fixed this issue.
